apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 12
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-deployment
        image: zephinzer/eg-whack-a-pod:api
        imagePullPolicy: Always
        ports:
        - containerPort: 8080