apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin-deployment
        image: tommeulensteen/whack-a-pod:admin
        imagePullPolicy: Always
        env:
          - name: APIIMAGE
            value: zephinzer/eg-whack-a-pod:api
        ports:
        - containerPort: 8080