---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: whack-a-pod
spec:
  replicas: 12
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - image: tommeulensteen/whack-a-pod:api
        imagePullPolicy: IfNotPresent
        name: api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
