apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
  labels:
    app: game
spec:
  replicas: 4
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game-deployment
        image: tommeulensteen/whack-a-pod:game
        imagePullPolicy: Always
        ports:
        - containerPort: 8080